"""uuid product

Revision ID: 711e3c4aa82c
Revises: 436b97d48ff3
Create Date: 2026-01-08 18:16:03.107121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711e3c4aa82c'
down_revision: Union[str, Sequence[str], None] = '436b97d48ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('uuid_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'uuid_id')
    # ### end Alembic commands ###
